### ISSUE TITLE
".tabulatr-outer-wrapper .tabulatr-table-col" failed to @extend ".col-xs-12".

### ISSUE THREAD

**Issue by danielpclark** [metaminded/tabulatr2#33]
The error I get is:

> ".tabulatr-outer-wrapper .tabulatr-table-col" failed to @extend ".col-xs-12". The selector ".col-xs-12" was not found. Use "@extend .col-xs-12 !optional" if the extend should be able to fail.

I can write `@extend .col-xs-12;` in my Sass file and it works just fine.  But when I add `*= require tabulatr` to my Sass file it blows up with this error.

It may be because bootstrap is loaded after tabulatr in the Sass file.

``` sass
 *= require_tree .
 *= require_self
 *= require tabulatr
 *= require chosen
 */
@import "bootstrap-sprockets";
@import "bootstrap";
```

Is there an import for tabulatr I can put after @import bootstrap?

I'm using
Rails 4.1.8
Ruby 2.2.0.preview1
gem 'compass-rails', github: 'danielpclark/compass-rails' # (pull request 197)
gem 'sprockets', '~> 3.0.0.beta.6'
gem 'sass-rails', '~> 5.0.0'
gem 'sass', '~> 3.4.9'

These versions are working & tested with a full web application framework.  My rails app works without tabulatr2.

**Comment by mlt** [comment]
This issue pops up in web search, so I'll add it here as apparently twbs 4 drops xs suffix https://stackoverflow.com/a/41795300/673826
