### ISSUE TITLE
Multi-select OR filter for enums

### ISSUE THREAD

**Issue by bkildow** [metaminded/tabulatr2#38]
I have a rails enum field on my model, and would love the ability to have a multi select field which ORs these results together. For example my field is called "status". I would like filter and show all records with a status of 'canceled' or 'deferred'. Is this possible?

**Comment by Crunch09** [comment]
@bkildow I just added the `enum_multiselect` filter. It's not on rubygems yet, only in the git version. Please try it out, hope it helps!
Usage:
```ruby
column :status, filter: :enum_multiselect
```

**Comment by bkildow** [comment]
This works great! Thanks!
