### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by madej** [metaminded/tabulatr2#45]
In  tabulatr2/lib/tabulatr/data/pagination.rb
```ruby
  def compute_pagination(page, pagesize)
    count = @relation.to_a.size
...
```
This is huge performance killer. You force full query to db, converting to hash all records, packing it in array and then counting it. And all you want here is just a number!

```ruby
  def compute_pagination(page, pagesize)
    count = @relation.count
...
```
is what you need here.

**Comment by Crunch09** [comment]
Thank you, you're absolutely right and i don't know why i changed this in the first place.
