### ISSUE TITLE
How to use current_user/pundit conditions in Tabulatr::Data?

### ISSUE THREAD

**Issue by mlt** [metaminded/tabulatr2#49]
Hi! I'm curious if there is a way to define buttons conditionally and/or set html attributes (disabled class) while defining data. It seems that I can't access my current_user or policy from Tabulatr::Data derived class. I started [SO question](http://stackoverflow.com/q/40517887/673826) as well.

**Comment by mlt** [comment]
[@controller](https://github.com/metaminded/tabulatr2/blob/master/lib/tabulatr/data/proxy.rb#L32).policy(r) works alright for pundit and buttons

**Comment by mlt** [comment]
It would be nice to mention it in the readme though...

**Comment by Crunch09** [comment]
@mlt Thanks! Want to submit a PR to include it in the README?

**Comment by mlt** [comment]
It seems that `@controller` is inaccessible from custom filter. Is it possible to make controller / session store accessible from filter block in data proxy?
I have a certain validity period and I want to show active record with a respect to *"now"* that user can alter.
